lesson-01 - MyController
pofoq/MetricsManager pull request #1
Opened 2021-04-22 08:59 UTC by pofoq

2021-04-22 18:49 UTC, Forkosigan requested changes

2021-04-22 18:49 UTC, Forkosigan commented on MetricsManager/Controllers/MyController.cs
> +    public class MyController : ControllerBase
Ни о чем не говорящее название класса. Классы надо именовать так, чтобы четко было понятно, какую отвественность несет класс. Из этого названия можно сделать вывод что этот контроллер предоставляет опреации над объектом My или пинадлежит вам, что ни о чем не говорит

2021-04-22 18:49 UTC, Forkosigan commented on MetricsManager/Controllers/MyController.cs
> +        public IActionResult Create([FromQuery] string date, [FromQuery] string temperature)
Зачем сюда передавать строку, когда можно сразу dateTime. Тогда дальше и парсинг не нужен. Аналогично температура int. аналогично применимо ко всем методам контроллера

2021-04-22 18:49 UTC, Forkosigan commented on MetricsManager/Controllers/MyController.cs
> +        [HttpPut("update2")]
почепму именно 2? О чем это должно говорить потребителю вашего API?

2021-04-23 07:31 UTC, pofoq commented on MetricsManager/Controllers/MyController.cs
> +    public class MyController : ControllerBase
Исправил

2021-04-23 07:36 UTC, pofoq commented on MetricsManager/Controllers/MyController.cs
> +        public IActionResult Create([FromQuery] string date, [FromQuery] string temperature)
Виноват. Не подумал, что так можно))

2021-04-23 07:37 UTC, pofoq commented on MetricsManager/Controllers/MyController.cs
> +        [HttpPut("update2")]
Это Я экспериментировал, по какому URI будет запускаться метод: по имени метода или по параметру в HttpPut.
Исправил.

2021-04-26 15:20 UTC, merged